# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'web-app-image'
  dockerfilePath: 'Users/lukerobinson/Downloads/AzureDevOps/Web-App-DevOps-Project/dockerfile/Dockerfile'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'devops-project-docker-sc'  # Update with your Docker registry service connection
    repository: $(imageName)
    command: 'build'
    Dockerfile: $(dockerfilePath)
