# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'  # Your service connection name
    repository: 'lukerobinson98/web-app-image'  # Your Docker Hub repository
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'  # Path to your Dockerfile in GitHub repo
    tags: 'v1'  # Tag for the image

- task: KubernetesManifest@1
  inputs: 
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'aks-service-connection'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'
