apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: flask-app
  template: 
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: lukerobinson98/web-app-image:v1
        ports:
        - containerPort: 8050
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata: 
  name: flask-app-service
spec: 
  selector:
    app: flask-app
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8050
  type: ClusterIP